language: go
go: 
 - "1.12"

addons:
  apt:
    packages:
    # needed for the nfpm pipe:
    - rpm
    # needed for the snap pipe:
    - snapd

env:
  - GO111MODULE=on PATH=/snap/bin:$PATH

script:
  - go build

install:
  # needed for the snap pipe:
  - sudo snap install snapcraft --classic
  - go mod download

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux